# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mntp_pb2 as mntp__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mntp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MNTP_ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTimeSyncRequest = channel.unary_unary(
                '/exodus_mntp.MNTP_Service/ProcessTimeSyncRequest',
                request_serializer=mntp__pb2.MNTP_Packet.SerializeToString,
                response_deserializer=mntp__pb2.MNTP_Packet.FromString,
                _registered_method=True)


class MNTP_ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessTimeSyncRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MNTP_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTimeSyncRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTimeSyncRequest,
                    request_deserializer=mntp__pb2.MNTP_Packet.FromString,
                    response_serializer=mntp__pb2.MNTP_Packet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exodus_mntp.MNTP_Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exodus_mntp.MNTP_Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MNTP_Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessTimeSyncRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exodus_mntp.MNTP_Service/ProcessTimeSyncRequest',
            mntp__pb2.MNTP_Packet.SerializeToString,
            mntp__pb2.MNTP_Packet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
