# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mntp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mntp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmntp.proto\x12\x0b\x65xodus_mntp\"\xd9\x01\n\x0bMNTP_Packet\x12\x0e\n\x06Header\x18\x01 \x01(\x05\x12\x11\n\tRootDelay\x18\x02 \x01(\x05\x12\x12\n\nDispersion\x18\x03 \x01(\x05\x12\x13\n\x0bReferenceID\x18\x04 \x01(\x05\x12\x1a\n\x12ReferenceTimestamp\x18\x05 \x01(\x03\x12\x17\n\x0fOriginTimestamp\x18\x06 \x01(\x03\x12\x18\n\x10ReceiveTimestamp\x18\x07 \x01(\x03\x12\x19\n\x11TransmitTimestamp\x18\x08 \x01(\x03\x12\x14\n\x0cSHA2Checksum\x18\t \x01(\t2^\n\x0cMNTP_Service\x12N\n\x16ProcessTimeSyncRequest\x12\x18.exodus_mntp.MNTP_Packet\x1a\x18.exodus_mntp.MNTP_Packet\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mntp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MNTP_PACKET']._serialized_start=28
  _globals['_MNTP_PACKET']._serialized_end=245
  _globals['_MNTP_SERVICE']._serialized_start=247
  _globals['_MNTP_SERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
